// src/lib/icd10-rural.ts
// Frontend mirror of supabase/functions/_shared/icd10-rural.ts (code → title).
// Used by the cockpit to render meaningful ICD-10 chips (e.g. "I21.9 — Acute
// myocardial infarction") instead of bare codes. Keep in sync with the
// edge-function catalogue — that file is the source of truth for grounding.

export const ICD10_TITLES: Record<string, string> = {
  // Cardiovascular
  'I20.0': 'Unstable angina',
  'I20.9': 'Angina pectoris, unspecified',
  'I21.9': 'Acute myocardial infarction, unspecified',
  'I21.3': 'ST-elevation myocardial infarction (STEMI)',
  'I50.9': 'Heart failure, unspecified',
  'I10': 'Essential (primary) hypertension',
  'I48.9': 'Atrial fibrillation and flutter, unspecified',
  'I26.9': 'Pulmonary embolism without acute cor pulmonale',
  'I71.0': 'Dissection of aorta',
  'I80.2': 'Phlebitis/thrombophlebitis of lower extremity (DVT)',
  'R07.4': 'Chest pain, unspecified',
  'R00.0': 'Tachycardia, unspecified',
  'R57.0': 'Cardiogenic shock',
  // Respiratory
  'J06.9': 'Acute upper respiratory infection, unspecified',
  'J00': 'Acute nasopharyngitis (common cold)',
  'J02.9': 'Acute pharyngitis, unspecified',
  'J03.9': 'Acute tonsillitis, unspecified',
  'J20.9': 'Acute bronchitis, unspecified',
  'J18.9': 'Pneumonia, unspecified organism',
  'J22': 'Unspecified acute lower respiratory infection',
  'J44.9': 'Chronic obstructive pulmonary disease (COPD)',
  'J44.1': 'COPD with acute exacerbation',
  'J45.9': 'Asthma, unspecified',
  'J46': 'Status asthmaticus (acute severe asthma)',
  'J81': 'Pulmonary oedema',
  'J93.9': 'Pneumothorax, unspecified',
  'R04.2': 'Haemoptysis',
  'R06.0': 'Dyspnoea (breathlessness)',
  'R05': 'Cough',
  // TB
  'A15.0': 'Tuberculosis of lung, confirmed',
  'A16.2': 'Tuberculosis of lung, without confirmation',
  'A15.9': 'Respiratory tuberculosis, unspecified',
  // Neuro / stroke
  'I63.9': 'Cerebral infarction, unspecified (ischaemic stroke)',
  'I61.9': 'Intracerebral haemorrhage, unspecified',
  'I64': 'Stroke, not specified as haemorrhage or infarction',
  'G45.9': 'Transient cerebral ischaemic attack (TIA)',
  'G40.9': 'Epilepsy, unspecified',
  'G41.9': 'Status epilepticus, unspecified',
  'R56.8': 'Other and unspecified convulsions',
  'G03.9': 'Meningitis, unspecified',
  'G04.9': 'Encephalitis, myelitis, unspecified',
  'R51': 'Headache',
  'R55': 'Syncope and collapse',
  'R42': 'Dizziness and giddiness',
  'R40.2': 'Coma, unspecified',
  // Obstetric
  'O14.9': 'Pre-eclampsia, unspecified',
  'O15.9': 'Eclampsia, unspecified as to time period',
  'O13': 'Gestational hypertension',
  'O20.0': 'Threatened abortion',
  'O46.9': 'Antepartum haemorrhage, unspecified',
  'O72.1': 'Other immediate postpartum haemorrhage',
  'O21.0': 'Mild hyperemesis gravidarum',
  'O23.4': 'Unspecified genitourinary tract infection in pregnancy',
  'O26.9': 'Pregnancy-related condition, unspecified',
  'Z34.9': 'Supervision of normal pregnancy, unspecified',
  'Z33.1': 'Pregnant state, incidental',
  // Paediatric / sepsis / dehydration / malnutrition
  'J21.9': 'Acute bronchiolitis, unspecified',
  'P36.9': 'Bacterial sepsis of newborn, unspecified',
  'A41.9': 'Sepsis, unspecified organism',
  'R65.2': 'Severe sepsis',
  'E86.0': 'Dehydration',
  'E86.1': 'Hypovolaemia',
  'R62.5': 'Failure to thrive / lack of expected development',
  'E43': 'Severe protein-energy malnutrition, unspecified',
  'E41': 'Nutritional marasmus',
  'E40': 'Kwashiorkor',
  // Fever / infectious
  'R50.9': 'Fever, unspecified',
  'A90': 'Dengue fever (classical)',
  'A91': 'Dengue haemorrhagic fever',
  'B54': 'Unspecified malaria',
  'B50.9': 'Plasmodium falciparum malaria, unspecified',
  'A01.0': 'Typhoid fever',
  'A75.9': 'Typhus fever, unspecified (scrub typhus)',
  'A27.9': 'Leptospirosis, unspecified',
  'B01.9': 'Varicella (chickenpox) without complication',
  'B05.9': 'Measles without complication',
  'A37.9': 'Whooping cough, unspecified species',
  'A35': 'Other tetanus',
  // GI
  'A09': 'Diarrhoea & gastroenteritis, presumed infectious',
  'A09.0': 'Other and unspecified gastroenteritis/colitis, infectious',
  'K59.1': 'Functional diarrhoea',
  'A03.9': 'Shigellosis, unspecified',
  'A00.9': 'Cholera, unspecified',
  'K35.8': 'Acute appendicitis, other and unspecified',
  'K35.2': 'Acute appendicitis with generalized peritonitis',
  'K65.0': 'Acute peritonitis',
  'K25.9': 'Gastric ulcer, unspecified',
  'K27.9': 'Peptic ulcer, site unspecified',
  'K92.2': 'Gastrointestinal haemorrhage, unspecified',
  'K80.2': 'Calculus of gallbladder without cholecystitis',
  'K81.0': 'Acute cholecystitis',
  'K85.9': 'Acute pancreatitis, unspecified',
  'K56.6': 'Intestinal obstruction, other and unspecified',
  'R10.0': 'Acute abdomen',
  'R10.4': 'Other and unspecified abdominal pain',
  'R11': 'Nausea and vomiting',
  'B82.9': 'Intestinal parasitism, unspecified',
  'B15.9': 'Acute hepatitis A without hepatic coma',
  // Metabolic / endocrine
  'E11.9': 'Type 2 diabetes mellitus without complications',
  'E10.1': 'Type 1 diabetes mellitus with ketoacidosis',
  'E14.1': 'Unspecified diabetes mellitus with ketoacidosis (DKA)',
  'E16.2': 'Hypoglycaemia, unspecified',
  'E87.6': 'Hypokalaemia',
  'E05.9': 'Thyrotoxicosis, unspecified',
  'E03.9': 'Hypothyroidism, unspecified',
  'D50.9': 'Iron deficiency anaemia, unspecified',
  'D64.9': 'Anaemia, unspecified',
  // Envenomation / exposure / poisoning
  'T63.0': 'Toxic effect of snake venom',
  'T63.3': 'Toxic effect of spider venom',
  'T63.4': 'Toxic effect of venom of other arthropod (scorpion)',
  'W59': 'Bitten or crushed by other reptiles',
  'Z20.3': 'Contact with/exposure to rabies',
  'W54': 'Bitten or struck by dog',
  'A82.9': 'Rabies, unspecified',
  'T60.9': 'Toxic effect of pesticide, unspecified (OP poisoning)',
  'T65.9': 'Toxic effect of unspecified substance',
  'X68': 'Intentional self-poisoning by pesticides',
  // Mental health
  'F32.9': 'Depressive episode, unspecified',
  'F41.9': 'Anxiety disorder, unspecified',
  'F43.1': 'Post-traumatic stress disorder',
  'R45.851': 'Suicidal ideation',
  'F20.9': 'Schizophrenia, unspecified',
  'F10.9': 'Mental/behavioural disorder due to alcohol use',
  'F99': 'Mental disorder, not otherwise specified',
  // Burns / trauma
  'T30.0': 'Burn of unspecified body region, unspecified degree',
  'T31.0': 'Burns involving less than 10% of body surface',
  'T31.2': 'Burns involving 20-29% of body surface',
  'T07': 'Unspecified multiple injuries',
  'S06.9': 'Intracranial injury, unspecified (head injury)',
  'S72.9': 'Fracture of femur, part unspecified',
  'T14.9': 'Injury, unspecified',
  'W19': 'Unspecified fall',
  'V89.2': 'Person injured in motor-vehicle accident',
  'T79.4': 'Traumatic shock',
  // Genitourinary
  'N39.0': 'Urinary tract infection, site not specified',
  'N10': 'Acute tubulo-interstitial nephritis (acute pyelonephritis)',
  'N23': 'Unspecified renal colic',
  'N17.9': 'Acute kidney failure, unspecified',
  // Skin / ENT / eye / MSK tail
  'L03.9': 'Cellulitis, unspecified',
  'L08.9': 'Local infection of skin/subcutaneous tissue, unspecified',
  'B35.9': 'Dermatophytosis (fungal skin infection), unspecified',
  'L30.9': 'Dermatitis, unspecified',
  'H66.9': 'Otitis media, unspecified',
  'H10.9': 'Conjunctivitis, unspecified',
  'H57.1': 'Ocular pain',
  'M54.5': 'Low back pain',
  'M79.1': 'Myalgia',
  'M25.5': 'Pain in joint',
  'K08.9': 'Disorder of teeth and supporting structures (toothache)',
  'R21': 'Rash and other nonspecific skin eruption',
  'R53': 'Malaise and fatigue',
  'Z00.0': 'General adult medical examination',
  'Z71.9': 'Counselling, unspecified',
};

export function icd10Title(code: string): string | null {
  return ICD10_TITLES[(code ?? '').trim().toUpperCase()] ?? null;
}
