// Auto-generated by `supabase gen types typescript`.
// Run: npx supabase gen types typescript --project-id hxgsxdtrnebpvbtdqwru > src/integrations/supabase/types.ts
// Placeholder until migrations are applied — regenerate after `db push`.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>; // regenerate after migrations apply
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
